image:
  repository: portainer/portainer-ee
  tag: 2.17.1
service:
  type: ClusterIP
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "103.212.54.71/32,138.68.192.41/32"
  hosts:
  - host: am-ae-demo-portainer-01.portainercloud.io
    paths:
    - path: /
  tls:
  - hosts:
    - am-ae-demo-portainer-01.portainercloud.io
    secretName: portainer-tls