apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-demo
  namespace: dev
spec:
  secretName: dev-podinfo-tls
  dnsNames:
  - am-ae-demo-app.portainercloud.io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer