apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 'v1.11.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: true
    volumes:
    - name: issuers
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "issuers"
    volumeMounts:
    - name: issuers
      mountPath: "/mnt/secrets-store/issuers"
      readOnly: true