apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: issuers
  namespace: cert-manager
spec:
  provider: azure
  secretObjects:
  - secretName: letsencrypt-prod
    type: opaque
    data:
    - key: tls.key
      objectName: letsencrypt-prod-key
  - secretName: letsencrypt-staging
    type: opaque
    data:
    - key: tls.key
      objectName: letsencrypt-staging-key
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 1023d285-3237-4b15-bab9-ef9e3f822056
    subscriptionId: b4429e9e-27fe-4347-a5ae-ce56b25d0367
    tenantId: 34d4c73d-4fff-4352-9ce2-df14c8d839f5
    keyvaultName: peaekv01
    resourceGroup: pe-azure-meetup
    objects: |
      array:
        - |
          objectName: letsencrypt-prod-key
          objectType: secret
        - |
          objectName: letsencrypt-staging-key
          objectType: secret