apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-demo
  namespace: portainer
spec:
  secretName: portainer-tls
  dnsNames:
  - am-ae-demo-portainer-01.portainercloud.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer