# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: portainer
#   namespace: portainer
# spec:
#   releaseName: portainer
#   targetNamespace: portainer
#   interval: 5m
#   chart:
#     spec:
#       chart: portainer
#       version: '1.0.40'
#       sourceRef:
#         kind: HelmRepository
#         name: portainer
#         namespace: flux-system
#       interval: 1m
#   values:
#     image:
#       repository: portainer/portainer-ee
#       tag: 2.17.1
#     service:
#       type: ClusterIP
#     ingress:
#       enabled: true
#       ingressClassName: nginx
#       annotations:
#         cert-manager.io/cluster-issuer: letsencrypt-staging
#         acme.cert-manager.io/http01-ingress-class: nginx
#         nginx.ingress.kubernetes.io/ssl-redirect: "true"
#         nginx.ingress.kubernetes.io/whitelist-source-range: "103.212.54.71/32,138.68.192.41/32"
#       hosts:
#       - host: am-demo.portainercloud.io
#         paths:
#         - path: /
#       tls:
#       - hosts:
#         - am-demo.portainercloud.io
#         secretName: portainer-tls