apiVersion: v1
kind: Service
metadata:
  name: portainer-demo-melbourne
  namespace: dev
  labels:
    app: portainer-demo-melbourne
spec:
  type: ClusterIP
  ports:
  - port: 9898
    targetPort: 9898
    protocol: TCP
    name: http
  selector:
    app: portainer-demo-melbourne
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-demo-melbourne
  namespace: dev
  labels:
    app: portainer-demo-melbourne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer-demo-melbourne
  template:
    metadata:
      labels:
        app: portainer-demo-melbourne
    spec:
      containers:
      - name: podinfo
        image: peazuremeetupacr.azurecr.io/podinfo:latest
        ports:
        - containerPort: 9898
        imagePullPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-demo-melbourne
  namespace: dev
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: azure-application-gateway
  tls:
  - hosts:
    - am-as-demo-app-01.portainercloud.io
    secretName: dev-podinfo-tls
  rules:
  - host: am-as-demo-app-01.portainercloud.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portainer-demo-melbourne
            port:
              number: 9898